configured

diff --git a/deploy/aks/Jenkinsfile b/deploy/aks/Jenkinsfile
--- a/deploy/aks/Jenkinsfile
+++ b/deploy/aks/Jenkinsfile
@@ -31,6 +31,7 @@ def verifyEnvironment = { service ->
       done
     """
 }
+
 pipeline {
     agent any
     tools {
@@ -41,111 +42,129 @@ pipeline {
     stages {
 
         stage('SCM') {
-            checkout scm
-        }
-
-        stage('Build') {
-            withCredentials([azureServicePrincipal(servicePrincipalId)]) {
-                sh """
-                    az login --service-principal -u "\$AZURE_CLIENT_ID" -p "\$AZURE_CLIENT_SECRET" -t "\$AZURE_TENANT_ID"
-                    az account set --subscription "\$AZURE_SUBSCRIPTION_ID"
-
-                    set +x
-                    export DOCUMENTDB_URI="\$(az cosmosdb show -g "${cosmosResourceGroup}" -n "${cosmosDbName}" --query documentEndpoint -o tsv)"
-                    export DOCUMENTDB_KEY="\$(az cosmosdb list-keys -g "${cosmosResourceGroup}" -n "${cosmosDbName}" --query primaryMasterKey -o tsv)"
-                    export DOCUMENTDB_DBNAME="${dbName}"
-                    set -x
-
-                    sh ./mvnw clean package
-                    az logout
-                """
+            steps {
+                checkout scm    
             }
         }
 
-        stage('Docker Image') {
-            withDockerRegistry([credentialsId: dockerCredentialId, url: "http://${dockerRegistry}"]) {
-                dir('target') {
+        stage('Build') {
+            steps {
+                withCredentials([azureServicePrincipal(servicePrincipalId)]) {
                     sh """
-                        cp -f ../src/aks/Dockerfile .
-                        docker build -t "${env.IMAGE_TAG}" .
-                        docker push "${env.IMAGE_TAG}"
+                        az login --service-principal -u "\$AZURE_CLIENT_ID" -p "\$AZURE_CLIENT_SECRET" -t "\$AZURE_TENANT_ID"
+                        az account set --subscription "\$AZURE_SUBSCRIPTION_ID"
+
+                        set +x
+                        export DOCUMENTDB_URI="\$(az cosmosdb show -g "${cosmosResourceGroup}" -n "${cosmosDbName}" --query documentEndpoint -o tsv)"
+                        export DOCUMENTDB_KEY="\$(az cosmosdb list-keys -g "${cosmosResourceGroup}" -n "${cosmosDbName}" --query primaryMasterKey -o tsv)"
+                        export DOCUMENTDB_DBNAME="${dbName}"
+                        set -x
+
+                        sh ./mvnw clean package
+                        az logout
                     """
                 }
             }
         }
 
-        stage('Check Env') {
-            // check the current active environment to determine the inactive one that will be deployed to
+        stage('Docker Image') {
+            steps {
+                withDockerRegistry([credentialsId: dockerCredentialId, url: "http://${dockerRegistry}"]) {
+                    dir('target') {
+                        sh """
+                            cp -f ../src/aks/Dockerfile .
+                            docker build -t "${env.IMAGE_TAG}" .
+                            docker push "${env.IMAGE_TAG}"
+                        """
+                    }
+                }
+            }
+        }
 
-            withCredentials([azureServicePrincipal(servicePrincipalId)]) {
-                // fetch the current service configuration
+        stage('Check Env') {
+            steps {
+                // check the current active environment to determine the inactive one that will be deployed to
+
+                withCredentials([azureServicePrincipal(servicePrincipalId)]) {
+                    // fetch the current service configuration
+                    sh """
+                      az login --service-principal -u "\$AZURE_CLIENT_ID" -p "\$AZURE_CLIENT_SECRET" -t "\$AZURE_TENANT_ID"
+                      az account set --subscription "\$AZURE_SUBSCRIPTION_ID"
+                      az aks get-credentials --resource-group "${resourceGroup}" --name "${aks}" --admin --file kubeconfig
+                      az logout
+                      current_role="\$(kubectl --kubeconfig kubeconfig get services todoapp-service --output json | jq -r .spec.selector.role)"
+                      if [ "\$current_role" = null ]; then
+                          echo "Unable to determine current environment"
+                          exit 1
+                      fi
+                      echo "\$current_role" >current-environment
+                    """
+                }
+
+                // parse the current active backend
+                currentEnvironment = readFile('current-environment').trim()
+
+                // set the build name
+                echo "***************************  CURRENT: $currentEnvironment     NEW: ${newEnvironment()}  *****************************"
+                currentBuild.displayName = newEnvironment().toUpperCase() + ' ' + imageName
+
+                env.TARGET_ROLE = newEnvironment()
+
+                // clean the inactive environment
                 sh """
-                  az login --service-principal -u "\$AZURE_CLIENT_ID" -p "\$AZURE_CLIENT_SECRET" -t "\$AZURE_TENANT_ID"
-                  az account set --subscription "\$AZURE_SUBSCRIPTION_ID"
-                  az aks get-credentials --resource-group "${resourceGroup}" --name "${aks}" --admin --file kubeconfig
-                  az logout
-                  current_role="\$(kubectl --kubeconfig kubeconfig get services todoapp-service --output json | jq -r .spec.selector.role)"
-                  if [ "\$current_role" = null ]; then
-                      echo "Unable to determine current environment"
-                      exit 1
-                  fi
-                  echo "\$current_role" >current-environment
+                kubectl --kubeconfig=kubeconfig delete deployment "todoapp-deployment-\$TARGET_ROLE"
                 """
             }
-
-            // parse the current active backend
-            currentEnvironment = readFile('current-environment').trim()
-
-            // set the build name
-            echo "***************************  CURRENT: $currentEnvironment     NEW: ${newEnvironment()}  *****************************"
-            currentBuild.displayName = newEnvironment().toUpperCase() + ' ' + imageName
-
-            env.TARGET_ROLE = newEnvironment()
-
-            // clean the inactive environment
-            sh """
-            kubectl --kubeconfig=kubeconfig delete deployment "todoapp-deployment-\$TARGET_ROLE"
-            """
         }
 
         stage('Deploy') {
-            // Apply the deployments to AKS.
-            // With enableConfigSubstitution set to true, the variables ${TARGET_ROLE}, ${IMAGE_TAG}, ${KUBERNETES_SECRET_NAME}
-            // will be replaced with environment variable values
-            acsDeploy azureCredentialsId: servicePrincipalId,
-                      resourceGroupName: resourceGroup,
-                      containerService: "${aks} | AKS",
-                      configFilePaths: 'src/aks/deployment.yml',
-                      enableConfigSubstitution: true,
-                      secretName: dockerRegistry,
-                      containerRegistryCredentials: [[credentialsId: dockerCredentialId, url: "http://${dockerRegistry}"]]
+            steps {
+                // Apply the deployments to AKS.
+                // With enableConfigSubstitution set to true, the variables ${TARGET_ROLE}, ${IMAGE_TAG}, ${KUBERNETES_SECRET_NAME}
+                // will be replaced with environment variable values
+                acsDeploy azureCredentialsId: servicePrincipalId,
+                          resourceGroupName: resourceGroup,
+                          containerService: "${aks} | AKS",
+                          configFilePaths: 'src/aks/deployment.yml',
+                          enableConfigSubstitution: true,
+                          secretName: dockerRegistry,
+                          containerRegistryCredentials: [[credentialsId: dockerCredentialId, url: "http://${dockerRegistry}"]]
+            }
         }
 
         stage('Verify Staged') {
+            steps{
             // verify the deployment through the corresponding test endpoint
             verifyEnvironment("todoapp-test-${newEnvironment()}")
+            }
         }
 
         stage('Switch') {
-            // Update the production service endpoint to route to the new environment.
-            // With enableConfigSubstitution set to true, the variables ${TARGET_ROLE}
-            // will be replaced with environment variable values
-            acsDeploy azureCredentialsId: servicePrincipalId,
-                      resourceGroupName: resourceGroup,
-                      containerService: "${aks} | AKS",
-                      configFilePaths: 'src/aks/service.yml',
-                      enableConfigSubstitution: true
+            steps {
+                // Update the production service endpoint to route to the new environment.
+                // With enableConfigSubstitution set to true, the variables ${TARGET_ROLE}
+                // will be replaced with environment variable values
+                acsDeploy azureCredentialsId: servicePrincipalId,
+                          resourceGroupName: resourceGroup,
+                          containerService: "${aks} | AKS",
+                          configFilePaths: 'src/aks/service.yml',
+                          enableConfigSubstitution: true
+            }
         }
 
         stage('Verify Prod') {
-            // verify the production environment is working properly
-            verifyEnvironment('todoapp-service')
+            steps {
+                // verify the production environment is working properly
+                verifyEnvironment('todoapp-service')
+            }
         }
 
         stage('Post-clean') {
-            sh '''
-              rm -f kubeconfig
-            '''
+            steps {
+                sh '''
+                  rm -f kubeconfig
+                '''
+            }
         }
     }
 
